"""
Django settings for my_currency project.

Generated by 'django-admin startproject' using Django 4.1.4.

For more information on this file, see
https://docs.djangoproject.com/en/4.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.1/ref/settings/
"""

import socket
from typing import List

from .base import *  # pylint: disable=W0401,W0614

# Local development with docker
hostname, _, ips = socket.gethostbyname_ex(socket.gethostname())

# https://docs.djangoproject.com/en/dev/ref/settings/#debug
DEBUG = True

SECRET_KEY = "#hcfe86ax6j1(s4!7bytvutw587+$we(**ex945@5j+0d=#2l="

ALLOWED_HOSTS: List[str] = [".localhost", "127.0.0.1", "[::1]", ".ngrok.io"]  # type: ignore

# Application definition
# django-extensions
# ------------------------------------------------------------------------------
# https://django-extensions.readthedocs.io/en/latest/installation_instructions.html#configuration
INSTALLED_APPS += ["django_extensions", "debug_toolbar"]  # noqa: F405

# Django Debug Toolbar
MIDDLEWARE += ["debug_toolbar.middleware.DebugToolbarMiddleware"]  # noqa: F405
# Required for Docker
INTERNAL_IPS = [ip[: ip.rfind(".")] + ".1" for ip in ips] + ["127.0.0.1", "10.0.2.2"]

EMAIL_BACKEND = "django.core.mail.backends.console.EmailBackend"
