# Generated by Django 4.2.10 on 2024-02-18 23:15
# ruff: noqa
import uuid

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []  # type: ignore

    operations = [
        migrations.CreateModel(
            name="Provider",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("name", models.CharField(max_length=20)),
                ("priority", models.IntegerField()),
                (
                    "method",
                    models.CharField(
                        choices=[("GET", "GET request."), ("POST", "POST request.")],
                        max_length=6,
                    ),
                ),
                ("url", models.URLField()),
                ("access_key", models.CharField(max_length=300)),
            ],
            options={
                "verbose_name": "Provider",
                "verbose_name_plural": "Providers",
                "ordering": ["priority"],
            },
        ),
    ]
