# Generated by Django 4.2.10 on 2024-02-14 21:01
# ruff: noqa
import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []  # type: ignore

    operations = [
        migrations.CreateModel(
            name="Currency",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("code", models.CharField(max_length=3, unique=True)),
                ("name", models.CharField(db_index=True, max_length=20)),
                ("symbol", models.CharField(max_length=3)),
            ],
            options={
                "verbose_name": "Currency",
                "verbose_name_plural": "Currencies",
                "ordering": ["code"],
            },
        ),
        migrations.CreateModel(
            name="CurrencyExchangeRate",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("valuation_date", models.DateField(db_index=True)),
                (
                    "rate_value",
                    models.DecimalField(db_index=True, decimal_places=6, max_digits=18),
                ),
                (
                    "exchange_currency",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="currencies.currency",
                    ),
                ),
                (
                    "source_currency",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="exchanges",
                        to="currencies.currency",
                    ),
                ),
            ],
            options={
                "verbose_name": "CurrencyExchangeRate",
                "verbose_name_plural": "CurrencyExchangeRates",
                "ordering": ["valuation_date"],
            },
        ),
    ]
